export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FETCH_USERS = "FETCH_USERS_SUCCESSFUL";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS_SUCCESSFUL";
export const ADD_NEW_QUESTION = "CREATE_NEW_QUESTION";
